akameco/PixivDeck

app/containers/ColumnBookmark/index.js, app/containers/ColumnFollow/index.js, app/containers/ColumnManager/index.js, app/containers/ColumnRanking/index.js, app/containers/ColumnRankingR18/index.js, app/containers/ColumnSearch/index.js, app/containers/ColumnUserIllust/index.js, app/containers/Table/Table.js, app/util/scrollToTopBind.js
トップへ戻るの機能を修正
なお、現状型情報をうまく扱えてない。
=> Fix Scroll to top

.travis.yml, appveyor.yml
=> Update CI Settings

app/containers/BookmarkButton/actionTypes.js, app/containers/BookmarkButton/actions.js, app/containers/BookmarkButton/saga.js, app/containers/ColumnBookmark/saga.js
=> ブックマーク成功時にカラムを更新

.travis.yml, appveyor.yml
=> Tagのpushがある場合のみCIを走らせる

app/action.js, app/containers/AddColumnModal/AddColumnModal.js, app/containers/AddColumnModal/index.js, app/containers/AddColumnModal/messages.js, app/containers/ColumnHistory/actionTypes.js, app/containers/ColumnHistory/actions.js, app/containers/ColumnHistory/constants.js, app/containers/ColumnHistory/index.js, app/containers/ColumnHistory/messages.js, app/containers/ColumnHistory/reducer.js, app/containers/ColumnHistory/saga.js, app/containers/ColumnHistory/selectors.js, app/containers/ColumnManager/index.js, app/containers/ColumnManager/reducer.js, app/reducer.js, app/sagas.js, app/types/state.js
=> 閲覧履歴カラムを追加

app/containers/ColumnHistory/reducer.js, app/store.js
close #30 
indexeddbにversionのプレフィックスを付けることで修正。
=> storeの復元をバージョンが変更されたら破棄する

app/components/Box/index.js, app/containers/BoxContainer/index.js
=> カラムのみを表示が逆だったのを修正

app/components/BoxHeader/index.js, app/containers/BoxContainer/index.js, app/types/illust.js
Box の 表示速度が気になったので、ShouldCompoenentUpdateを使って高速化
=> Should Componet update

app/containers/ColumnBookmark/saga.js, app/containers/ColumnFollow/saga.js, app/containers/ColumnSearch/saga.js, app/containers/FollowButton/actionTypes.js, app/containers/FollowButton/actions.js, app/containers/FollowButton/index.js, app/containers/FollowButton/saga.js, app/containers/Notify/saga.js, flow-typed/index.js
=> Add Notify

electron-builder.yml
related #83 
windowsのビルド設定にzipと7zipを追加。
=> Add build target

app/containers/Column/reducer.js, app/containers/Column/sagas.js, app/containers/ColumnRanking/actionTypes.js, app/containers/ColumnRanking/actions.js, app/containers/ColumnRanking/constants.js, app/containers/ColumnRanking/index.js, app/containers/ColumnRanking/reducer.js, app/containers/ColumnRanking/saga.js, app/containers/ColumnRanking/selectors.js, app/containers/ColumnRanking/tests/__snapshots__/reducer.test.js.snap, app/containers/ColumnRanking/tests/__snapshots__/sagas.test.js.snap, app/containers/ColumnRanking/tests/reducer.test.js, app/containers/ColumnRanking/tests/sagas.test.js
Close #44 
ランキングを3hに一度更新する処理を追加。
Update rankings every 3 hours.
=> Update rankings every 3 hours

app/main.development.js
自動更新時に強制再起動は自分で使っててうざかったので次回起動時に反映することにした。
強制アップデートする`autoUpdater.quitAndInstall()`の削除
=> Not restart when auto update

app/containers/ColumnFollow/saga.js
=> 新着へのイラストの追加の順番の修正

app/containers/LoginModal/actionTypes.js, app/containers/LoginModal/actions.js, app/containers/LoginModal/constants.js, app/containers/LoginModal/reducer.js, app/containers/LoginModal/saga.js, app/containers/LoginModal/selectors.js, app/containers/LoginModal/tests/__snapshots__/reducer.test.js.snap, app/containers/LoginModal/tests/reducer.test.js, app/containers/LoginModal/tests/selectors.test.js, app/types/account.js
=> Add types/account

app/containers/BoxContainer/tests/__snapshots__/sagas.test.js.snap, app/containers/BoxContainer/tests/sagas.test.js, app/containers/ColumnBookmark/saga.js, app/containers/ColumnBookmark/tests/__snapshots__/sagas.test.js.snap, app/containers/ColumnBookmark/tests/sagas.test.js, app/containers/ColumnFollow/saga.js, app/containers/ColumnSearch/saga.js
=> getMyIdを使ったそれぞれのsagaのリファクタリング

app/components/LazyLoadImg/index.js
完全に解決したわけじゃないけど、ある程度発生しずらくなったので修正済みにする。
クリティカルなものではないので様子見。
#close #31 
#close #33
=> Fix setState

app/containers/ColumnBookmark/saga.js, app/containers/ColumnBookmark/tests/__snapshots__/sagas.test.js.snap, app/containers/ColumnBookmark/tests/sagas.test.js
=> Fix Bookmark

app/components/LazyLoadImg/index.js
Reverts akameco/PixivDeck#97
よくわからないがバグる
=> Revert "Fix setState"

app/components/ColumnHeader/HeaderPopover.js, app/components/ColumnHeaderBookmark/index.js, app/containers/ColumnSearch/FilterUsersIn/__snapshots__/index.test.js.snap, app/containers/ColumnSearch/FilterUsersIn/index.js, app/containers/ColumnSearch/FilterUsersIn/index.test.js, app/containers/ColumnSearch/actionTypes.js, app/containers/ColumnSearch/actions.js, app/containers/ColumnSearch/constants.js, app/containers/ColumnSearch/index.js, app/containers/ColumnSearch/reducer.js, app/containers/ColumnSearch/saga.js, app/containers/ColumnSearch/selectors.js, app/containers/ColumnSearch/tests/__snapshots__/reducer.test.js.snap, app/containers/ColumnSearch/tests/reducer.test.js, app/containers/ColumnSearch/tests/sagas.test.js
=> Add UsersIn filter

app/i18n/__snapshots__/i18n.test.js.snap, app/i18n/en.yml
related #18
https://github.com/akameco/PixivDeck/issues/18#issuecomment-314722110
@volcbs Thank you 👍
=> Fix transraion

app/containers/ColumnBookmark/saga.js, app/containers/ColumnFollow/saga.js
close #107 
個々のsagaにtry/catchを追加した。
sagaは個々のエラーハンドリングをしっかりしないと、全体に伝播するので注意する必要がある。
=> Add error handle

app/containers/BookmarkButton/saga.js, app/services/api.js
related #109 
When bookmark success, call api for illust detail.
=> Fix 109 broken bookmark

app/main.development.js
ref https://github.com/akameco/PixivDeck/issues/109#issuecomment-315375030
=> Just call app.quit() when click window button at macOS

app/components/TwitterButton/styles.js, app/components/UserDrawer/Navigation.js
=> ドロワーにpixivで開くボタンを追加

package-lock.json, package.json
storybookがエラーで動作せず
モジュールを整理したら動いた
=> storybookの修正

app/i18n/zh.yml
I've finished the Chinese translation. If some phrases are too long or too short for the UI, you can inform me via email, and I'll polish it as soon as possible.
=> Finish Chinese translation.

.all-contributorsrc, package.json, readme.md, yarn.lock
=> Add all-contributorsrc

app/i18n/en.yml, app/i18n/zh.yml
=> R-18 description change + Some grammar issues

CODE_OF_CONDUCT.md, app/components/ColumnHeader/HeaderPopover.js, app/containers/AddColumnModal/index.js, app/containers/AddNewColumnButton/index.js, app/containers/ColumnRanking/index.js, app/containers/ColumnRecommended/index.js, app/containers/FollowButton/FollowButton.js, app/containers/FollowButton/index.js, app/containers/Language/index.js, app/services/api.js, package.json, yarn.lock
=> chore(npm): update pritter && code format

app/components/Box/BoxFooter.js, app/components/Box/boxStyles.js, app/components/ColumnBody/index.js, app/components/Profile/index.js
Each column is scrollable in X-axis. bu it will be stopping scroll crossing columns in X-axis in sometimes because columns are scrollable in X-axis.
So I've made to fluency scrolling for crossing columns.
- Added overflow-x property for illustrator's name
- Added overflow-x property for tag's div
- Added width property for colum body
- Added width property for tag's div
=> Fix width for columns

app/components/A/tests/__snapshots__/index.test.js.snap, app/main.development.js, app/services/api.test.js, package.json, yarn.lock
**What**:  Windows環境のビルドができないので一旦source-mapを外す
**Why**: 
**How**: 
**Checklist**:
=> fix(npm): remove sourcemap

app/containers/LoginModal/actionTypes.js, app/containers/LoginModal/actions.js, app/containers/LoginModal/constants.js, app/containers/LoginModal/reducer.js, app/containers/LoginModal/saga.js, app/containers/LoginModal/selectors.js, app/containers/LoginModal/tests/__snapshots__/reducer.test.js.snap, app/containers/LoginModal/tests/__snapshots__/selectors.test.js.snap, app/services/api.js
**What**: パスワードではなく、refresh_tokenを使うように変更
**Why**: resolved #149
**How**:  refreshTokenを保存しておき使い回し
**Checklist**:
=> feat(login): use refresh_token

app/store.js
**What**: メジャーバージョンのみキャッシュをクリアする
**Why**: パッチバージョンの更新でデータが飛ぶのがつらい
**How**: 
**Checklist**:
=> feat(store): majarバージョンのみcacheをクリア

app/main.development.js
**What**:  プロダクションでdebugを有効化
**Why**: 
**How**: 
**Checklist**:
=> feat(main): enable debug mode

app/store.js
**What**: 画像を開いたまま終了すると空白のページになる問題を修正
**Why**:  related #152, #146, #148.
**How**: IllustPreviewおよびMangaPreviewを保存しないようにした
**Checklist**:
=> fix(store): fix blank page

app/components/TwitterButton/index.js
**What**: caseの修正です。`twitter`から`Twitter`へ修正しました。細かくてすみません。
**Why**: サービス名の表記ミスであるため、違和感がある
**How**: `Button` componentの`label`属性の内容を修正しました。
**Checklist**:
=> Correct the case for Twitter

.travis.yml, package.json
**What**: flowをCI上で実行する
**Why**: 
**How**: 
**Checklist**:
=> build(travis): flowをtravisで実行
